pipeline {
    agent any

    tools {
        python 'Python3'  // Needs ShiningPanda plugin to provide Python installations
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/Eustusmurea/alx-backend-python.git',
                    credentialsId: '077f0262-c5f7-48ed-bb85-05d198594a77'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                    . venv/bin/activate
                    pytest --junitxml=report.xml --html=report.html --self-contained-html
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                    archiveArtifacts artifacts: 'messaging_app/report.html', fingerprint: true
                }
            }
        }
    }

    triggers {
        // No auto triggers -> you will run manually with "Build Now"
    }
}