# Generated by Django 5.2.4 on 2025-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.CharField(blank=True, default='General', max_length=255),
        ),
    ]
